workflows:
  simulator-workflow:
    name: Build for simulator
    environment:
      xcode: latest
    scripts:
      - name: Build with Generic Destination
        script: |
          xcodebuild build \
            -project "Humorize.xcodeproj" \
            -scheme "com.vagner.humorize" \
            -sdk iphonesimulator \
            -configuration Debug          
    artifacts:
      - /Users/builder/Library/Developer/Xcode/DerivedData/**/*.app
